name: Deploy Next.js App to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /var/www/tu-proyecto
            git pull origin main
            export NODE_ENV=production

         
            npm ci
            npx prisma generate || true # Solo si usas Prisma
            npm run build
            pm2 restart tu-proyecto
          EOF
