name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to Ubuntu Server via SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /var/www/upqroo-bolsa-empleo &&
            git pull &&
            npm ci --production &&
            npm run build &&
            pm2 restart bolsa-upqroo
          "
